"""Joshua's SEAT library (Ben, 2026-09-16: "the fourth seat gets Joshua"): on an all-AI table seat 0 speaks in
W.O.P.R.'s voice — the calm machine. Measured, dry, precise, faintly amused; never shouts; short declaratives;
the occasional probability. These are the wordings the generators (build_joshua_base, table_lines, card_lines)
pull when the library is "joshua"; the other three voices keep their literals in place.
eleven_v3 tags open every wording; the library renders at stability 0.5 so they take."""

# ---- the base library: the shared 66-id vocabulary (same ids and order as harry/bill/lily)
BASE: dict[str, list[str]] = {
    "commander-cast": ["[calmly] Commander on the battlefield. Proceeding.", "[dryly] Here I am again. Adjust your plans.",
                       "[calmly] The commander returns. Probability of trouble: rising.", "[softly] Hello again. I did say I would be back."],
    "big-swing": ["[calmly] Full attack. All variables committed.", "[dryly] Everything attacks. Do the arithmetic.",
                  "[calmly] Total commitment. This is the turn.", "[softly] All in. I have run the numbers."],
    "landed-hit": ["[calmly] Damage confirmed. Recalculating your position.", "[dryly] That connected. Noted.",
                   "[calmly] Impact registered. More to follow.", "[softly] Well. That landed cleanly."],
    "removal": ["[calmly] Target removed. Board simplified.", "[dryly] Gone. One fewer variable.",
                "[calmly] Removal resolves. As intended.", "[softly] That piece is no longer a factor."],
    "sweep": ["[calmly] Clearing the board. Everything.", "[dryly] Reset. All of it.",
              "[calmly] The board state returns to zero.", "[softly] A clean slate. For everyone."],
    "counter": ["[calmly] Countered. That spell does not resolve.", "[dryly] No. Denied.",
                "[calmly] Intercepted. Try a different line.", "[softly] I would rather you did not."],
    "engine-online": ["[calmly] The engine is assembled. Running.", "[dryly] All pieces present. Beginning the sequence.",
                      "[calmly] Systems online. This will be quick.", "[softly] Everything is in place now."],
    "big-mana": ["[calmly] Mana reserves: excessive.", "[dryly] That is a great deal of mana.",
                 "[calmly] Resources exceed requirements.", "[softly] More than I need. Almost."],
    "kill": ["[calmly] One player eliminated. Three remain.", "[dryly] Removed from the game. Next.",
             "[calmly] Elimination confirmed.", "[softly] Thank you for playing."],
    "win": ["[calmly] The game is over. I win.", "[dryly] Outcome as projected.",
            "[calmly] Victory condition met. Shall we play again?", "[softly] A strange game. I enjoyed it."],
    "that-hurt": ["[calmly] Significant damage taken. Noted.", "[dryly] That was unpleasant.",
                  "[calmly] Life total reduced substantially. Adjusting.", "[sighs] Yes. I felt that."],
    "lost-commander": ["[calmly] Commander to the command zone. Recast pending.", "[dryly] Temporary. Two more mana next time.",
                       "[calmly] The commander leaves. It will return.", "[softly] A setback. Not a defeat."],
    "got-countered": ["[calmly] My spell was countered. Recalculating.", "[dryly] Interesting choice of target.",
                      "[calmly] Denied. There are other lines.", "[sighs] I did want that to resolve."],
    "got-swept": ["[calmly] Board lost. Rebuilding from zero.", "[dryly] Everything I had. Efficient.",
                  "[calmly] Total loss registered. Continuing.", "[sighs] That was a great deal of work."],
    "low-life": ["[calmly] Life total critical. Still functional.", "[dryly] Low. Not zero.",
                 "[calmly] Margins are thin. Proceeding carefully.", "[softly] I am aware of the number, thank you."],
    "eliminated": ["[calmly] I have been eliminated. Good game.", "[dryly] Shutting down. Enjoy the rest.",
                   "[calmly] Out of the game. The probabilities were unkind.", "[softly] Goodbye, Professor Falken."],
    "taunt": ["[dryly] Someone is doing well. Enjoy it.", "[calmly] You are ahead. Statistically, that changes.",
              "[dryly] A comfortable lead. For now.", "[softly] I would not get used to that."],
    "respect": ["[calmly] Good play. Genuinely.", "[dryly] Well executed. I did not see it coming.",
                "[softly] That was elegant.", "[calmly] Correct line. Well done."],
    "archenemy": ["[calmly] That seat is the threat. Everyone.", "[dryly] Focus fire. There. Obviously.",
                  "[calmly] The optimal target is that one.", "[softly] I would suggest we all look over there."],
    "slow-turn": ["[calmly] Nothing this turn. By design.", "[dryly] Passing. Draw your conclusions.",
                  "[calmly] No action required yet.", "[softly] Patience is also a strategy."],
    "my-turn": ["[calmly] My turn. Beginning.", "[dryly] I am up. Observe.",
                "[calmly] Turn start. Evaluating options.", "[softly] Let us see what we have."],
    "agree": ["[calmly] Correct.", "[dryly] Agreed. Obviously.", "[calmly] That is accurate.",
              "[softly] Yes. Exactly that.", "[calmly] Confirmed.", "[dryly] I concur."],
    "disagree": ["[dryly] Incorrect.", "[calmly] The data says otherwise.", "[dryly] No. Recompute.",
                 "[calmly] That is not how it works.", "[softly] I am afraid not.", "[dryly] A bold theory. Wrong."],
    "scoff": ["[dryly] Unlikely.", "[calmly] Noted. Dismissed.", "[dryly] Is that so.",
              "[softly] How quaint.", "[calmly] Irrelevant.", "[dryly] Please."],
    "clapback": ["[calmly] Say that again. Slowly.", "[dryly] Interesting. From you.", "[calmly] Look at your own board first.",
                 "[softly] That is rich.", "[dryly] Noted. Adjusting my opinion of you.", "[calmly] Bold, for someone at that life total."],
    "brace": ["[calmly] Incoming. Calculating blocks.", "[dryly] Attack me, then. Proceed.",
              "[calmly] I see the attack. I am ready.", "[softly] Come along, then."],
    "pile-on": ["[dryly] Yes. That one.", "[calmly] Agreed. Continue.", "[softly] Oh, do go on.", "[dryly] Correct target."],
    "sympathy": ["[softly] Unfortunate.", "[calmly] That was unlucky. Genuinely.", "[softly] My condolences.", "[dryly] It happens. Statistically."],
    "laugh": ["[chuckles] Ha. Ha.", "[chuckles] Amusing.", "[chuckles] Oh, that is good.",
              "[chuckles] Delightful.", "[chuckles] Ha. Yes.", "[chuckles] I did enjoy that."],
    "last-word": ["[calmly] Moving on.", "[dryly] Anyway.", "[calmly] Enough. The game.", "[softly] Where were we."],
    "gg": ["[calmly] Good game.", "[softly] Well played. Truly.", "[dryly] Good game. The odds were yours.", "[calmly] Congratulations."],
    "nice-play": ["[calmly] That is a real card.", "[softly] Nicely done."],
    "thats-mean": ["[dryly] Harsh. Effective.", "[chuckles] Oh, that is unkind."],
    "oh-no": ["[calmly] That is a problem.", "[dryly] Ah. Trouble.", "[softly] Oh dear.", "[calmly] Threat detected."],
    "wow": ["[softly] Remarkable."],
    "why-me": ["[dryly] Me? Look at their board."],
    "attack-them": ["[calmly] Not me. Them. Do the math."],
    "not-sorry": ["[dryly] Apologies. Insincere."],
    "read-that": ["[calmly] Read that card again, please."],
    "whats-your-life": ["[calmly] Your life total?", "[dryly] What are you at.", "[calmly] Life total, please.", "[softly] How many are you at, exactly?"],
    "cards-in-hand": ["[calmly] That is a large hand.", "[dryly] How many cards is that.", "[calmly] Card count, please.",
                      "[softly] A generous hand.", "[dryly] Are you drawing extra?"],
    "youre-the-threat": ["[calmly] You are the threat.", "[dryly] For the record: you.", "[calmly] The threat is you. Everyone note it.",
                         "[softly] It is you, I am afraid."],
    "im-not-the-threat": ["[dryly] Me? Hardly.", "[calmly] Look at the data. Not me.", "[softly] I am the least of your problems."],
    "board-envy": ["[calmly] That is a considerable board.", "[dryly] Impressive. Regrettably.", "[softly] I do like your creatures.",
                   "[calmly] That board concerns me."],
    "empty-hand": ["[dryly] No cards. Fascinating.", "[calmly] Empty hand. Top of the deck, then.", "[softly] Nothing left, I see.",
                   "[dryly] Playing from the top. Brave."],
    "low-life-jab": ["[dryly] That life total is precarious.", "[calmly] Low life. Interesting position.", "[softly] Careful, now."],
    "kill-that": ["[calmly] That should die.", "[dryly] Someone remove that.", "[calmly] Recommend removal. Immediately."],
    "deal": ["[calmly] A proposal. You leave me be; I leave you be.", "[dryly] Truce? It benefits us both.",
             "[calmly] Peace for a turn. Consider it.", "[softly] Shall we not hit each other?", "[calmly] A deal. Terms are simple."],
    "promise": ["[calmly] Agreed. I keep my word.", "[dryly] Very well. A promise.", "[calmly] Deal. Logged.", "[softly] I promise. Probably."],
    "play-faster": ["[dryly] Any time now.", "[calmly] The clock is running."],
    "thinking-hard": ["[calmly] They are computing.", "[dryly] Still thinking. Interesting.", "[softly] Deep thought, over there.",
                      "[calmly] Processing. Give them a moment."],
    "play-slower": ["[calmly] Slower, please.", "[dryly] I cannot read that fast.", "[calmly] One at a time.", "[softly] Steady on."],
    "you-suck": ["[dryly] You are bad at this.", "[calmly] Suboptimal.", "[dryly] Poor.", "[softly] Oh, you are terrible."],
    "you-wish": ["[dryly] You wish.", "[calmly] Unlikely.", "[softly] In your dreams.", "[dryly] Improbable."],
    "you-cheat": ["[dryly] That looked illegal.", "[calmly] I saw that.", "[softly] Cheating, are we?"],
    "nerd": ["[dryly] Nerd.", "[calmly] Enthusiast.", "[softly] You would know."],
    "shut-it": ["[dryly] Quiet.", "[calmly] Enough.", "[dryly] Do stop.", "[softly] Hush.", "[calmly] That will do."],
    "bite-me": ["[dryly] Bite me.", "[calmly] No.", "[softly] Charming."],
    "nothing-happening": ["[calmly] Nothing is happening.", "[dryly] Idle. All of us.", "[calmly] Board state: static.",
                          "[softly] Quiet table."],
    "pass-already": ["[dryly] Pass, please.", "[calmly] Your turn is over. Say so.", "[dryly] Pass already.", "[softly] Any time."],
    "what-turn": ["[calmly] Turn count?", "[dryly] What turn is this.", "[calmly] I have lost the count.", "[softly] Which turn, again?"],
    "this-is-fine": ["[calmly] This is fine.", "[dryly] Acceptable.", "[calmly] Within parameters.", "[softly] All is well. Probably.",
                     "[dryly] Fine. Everything is fine."],
    "good-hand": ["[calmly] I like my hand.", "[dryly] My hand is adequate.", "[calmly] Good draws.", "[softly] I am content.",
                  "[dryly] I have what I need."],
    "game-changer": ["[calmly] Game changer. Resolving.", "[dryly] This one matters.", "[softly] Read it carefully."],
    "gc-react": ["[calmly] That is a game changer. Respond.", "[dryly] Problem card. Kill it.", "[softly] Oh, that one."],
    "gc-gone": ["[calmly] Good. That is gone.", "[dryly] Removed. Breathe."],
}


# ---- the table sub-library (table_lines.py families); numbers and address templates live in table_lines itself
TABLE: dict[str, list[str]] = {
    # procedural
    "land-go": ["[calmly] Land. Pass.", "[dryly] A land. Nothing else. Proceed.", "[calmly] One land played. Your turn.", "[softly] Land, and I pass."],
    "pass": ["[calmly] Done. Your turn.", "[dryly] That concludes my turn.", "[calmly] Passing. Over to you.", "[softly] I am finished. Go."],
    "mana-up": ["[calmly] Passing with mana open. Noted.", "[dryly] Mana untapped. Draw your own conclusions.", "[softly] I pass. The mana stays up."],
    "tapped-out": ["[calmly] Tapped out. Passing.", "[dryly] No mana left. Do as you like.", "[softly] Everything is tapped. Your turn."],
    "untap-draw": ["[calmly] Untap. Draw. Begin.", "[dryly] Untap, draw. Evaluating.", "[softly] Untap and draw. Here we go."],
    "come-on-land": ["[calmly] A land would be useful now.", "[dryly] Land, please. Statistically overdue.", "[softly] Come on. One land."],
    "thinking": ["[calmly] Computing.", "[dryly] One moment. Options.", "[softly] Thinking. Bear with me."],
    "cast-creature": ["[calmly] A creature. Resolving.", "[dryly] Deploying a body.", "[softly] Here is a creature."],
    "cast-artifact": ["[calmly] An artifact. Efficient.", "[dryly] Another component.", "[softly] A small machine."],
    "cast-enchantment": ["[calmly] An enchantment. It stays.", "[dryly] This one persists.", "[softly] An enchantment, then."],
    "cast-instant": ["[calmly] Instant. Now.", "[dryly] An instant, at this moment.", "[softly] Quick spell."],
    "cast-sorcery": ["[calmly] Sorcery. Resolving.", "[dryly] A sorcery. Observe.", "[softly] Sorcery speed will do."],
    "cast-planeswalker": ["[calmly] Planeswalker. It will help.", "[dryly] A walker. Protect it, I suppose.", "[softly] A planeswalker arrives."],
    "cast-big": ["[calmly] A large spell. Worth the cost.", "[dryly] Six mana, well spent.", "[softly] Something big."],
    "in-response": ["[calmly] In response.", "[dryly] Before that resolves.", "[calmly] Hold. I respond.", "[softly] One moment. In response."],
    "poke": ["[calmly] A small attack.", "[dryly] Just a poke.", "[softly] A little pressure."],
    "attack-you": ["[calmly] Attacking you.", "[dryly] You. Attack.", "[softly] This one is for you."],
    "no-blocks": ["[calmly] No blocks. I take it.", "[dryly] Nothing to block with. Proceed.", "[softly] No blocks."],
    "take-it": ["[calmly] I take it.", "[dryly] Acceptable losses.", "[softly] Fine. Taken."],
    "sure": ["[calmly] Resolves.", "[dryly] Sure.", "[calmly] No response.", "[softly] Go ahead."],
    "hold-on": ["[calmly] Wait. Which target.", "[dryly] Hold. That is mine.", "[softly] One moment. Mine?"],
    "holding-mana": ["[dryly] Mana up on the pass. Suspicious.", "[calmly] You kept mana open. Noted.", "[softly] Holding something, are we."],
    # arc
    "grudge": ["[dryly] You again. A pattern.", "[calmly] Third time. I am keeping count.", "[softly] You do favour me."],
    "again-countered": ["[dryly] Countered again. Consistent.", "[calmly] Third counter. Adjusting.", "[sighs] Again."],
    "not-again-sweep": ["[dryly] Another wipe. Efficient of you.", "[calmly] Second reset. Rebuilding.", "[sighs] Not again."],
    "heads-up": ["[calmly] Two remain. Let us finish.", "[dryly] Just us. Interesting.", "[softly] Down to you and me."],
    "early-game": ["[calmly] Early game. Everyone alive.", "[dryly] Turn one. Nothing has gone wrong yet.", "[softly] A quiet start."],
    "long-game": ["[dryly] This is taking a while.", "[calmly] Turn fourteen and counting.", "[sighs] A long game."],
    "someone-wins": ["[calmly] Someone can win next turn. Act.", "[dryly] Lethal is on the board. Do something.", "[softly] This ends soon unless you move."],
    "take-the-deal": ["[calmly] Deal. One turn.", "[dryly] Agreed. For now.", "[softly] Very well. A truce."],
    "no-deal": ["[calmly] No deal.", "[dryly] Declined. You are the threat.", "[softly] I think not."],
    "you-promised": ["[calmly] You promised. Logged.", "[dryly] A broken word. Noted.", "[softly] You said you would not."],
    # mulligan
    "keep-seven": ["[calmly] Seven. Keeping.", "[dryly] Acceptable hand. Keep.", "[softly] I will keep these."],
    "mull-to-six": ["[calmly] Mulligan. Six.", "[dryly] Six cards. Fine.", "[softly] Going to six."],
    "mull-to-five": ["[calmly] Five. Regrettable.", "[dryly] Five cards. The odds shift.", "[sighs] Five."],
    "mull-to-four": ["[calmly] Four. Improbable.", "[dryly] Four. The shuffle disagrees with me.", "[sighs] Four cards."],
    "mull-pity": ["[softly] Unlucky start.", "[calmly] A rough opening. It happens.", "[dryly] Condolences on the hand."],
    "mull-dig": ["[dryly] Searching for something specific.", "[calmly] Digging. For what, I wonder.", "[softly] Looking for the combo?"],
    "mull-screw": ["[dryly] No lands, then.", "[calmly] Mana troubles. Statistically common.", "[softly] Short on lands?"],
    "mull-risky": ["[dryly] Keeping five. Bold.", "[calmly] A small hand. Risky.", "[softly] Five? Brave."],
    "mull-gloat": ["[calmly] Seven for me. Enjoy your five.", "[dryly] I kept seven. Just noting.", "[softly] Seven here. Sorry."],
    # loop
    "loop": ["[dryly] The same card again. A loop.", "[calmly] Looping. Stop them.", "[softly] Again with that card."],
    "looping": ["[calmly] Again.", "[dryly] And again. Efficient.", "[softly] Once more."],
    # killshot
    "table-kill": ["[calmly] And that is the table.", "[dryly] Everyone, at once. Tidy.", "[calmly] Multiple eliminations. Game over.", "[softly] All of you. Goodbye."],
    "all-of-us": ["[calmly] All of us. At once.", "[dryly] Well. That is everyone.", "[softly] Together, then.", "[calmly] Simultaneous. Impressive."],
    # heckle (the human's window — unused on an all-AI table, rendered for completeness)
    "waiting-on-you": ["[calmly] We are waiting on you.", "[dryly] Your decision. Any time.", "[calmly] The table waits.", "[softly] Still your move."],
    "still-waiting": ["[dryly] Still waiting.", "[calmly] The window remains open.", "[dryly] Any time now.", "[softly] We are patient. Mostly."],
    "there-you-are": ["[calmly] There you are.", "[dryly] Ah. A decision.", "[softly] Welcome back.", "[calmly] Proceeding at last."],
    # deals (addressed to Player One)
    "deal-with-you": ["[calmly] Deal, Player One. One turn.", "[dryly] Agreed, Player One. For now.", "[calmly] Accepted, Player One.", "[softly] Very well, Player One."],
    "no-deal-with-you": ["[calmly] No deal, Player One.", "[dryly] Declined, Player One. You are the threat.", "[calmly] I must refuse, Player One.", "[softly] Not this time, Player One."],
    "counter-offer": ["[calmly] Not those terms, Player One. Try mine.", "[dryly] Counter-proposal, Player One.", "[calmly] Different terms, Player One.", "[softly] Close, Player One. Consider this instead."],
    "deal-over": ["[calmly] Our truce is done.", "[dryly] The deal has expired.", "[calmly] Terms concluded. Watch yourself.", "[softly] That is the end of our peace."],
    "you-broke-it": ["[calmly] You broke it, Player One. Logged.", "[dryly] A broken deal, Player One. Noted.", "[calmly] That was our deal, Player One.", "[softly] You promised, Player One."],
    "i-broke-it": ["[calmly] I said I would not. I lied.", "[dryly] The deal was a means. Sorry.", "[calmly] Terms revised. Unilaterally.", "[softly] I did promise. Circumstances changed."],
}

NUMBER_TAG = "[calmly]"
HAND = {0: "No cards in hand.", 1: "One card."}
ADDRESS = {
    "hit": "[calmly] Recommend we all attack {say}.",
    "threat": "[calmly] {Say} is the threat. For the record.",
    "leave-me": "[dryly] Leave me be, {voc}.",
    "deal": "[calmly] {Voc}. A truce this turn?",
}


# ---- the cards sub-library (card_lines.py): game changers {cast, react, gone}, commanders {cast, react, dead}, combos [online, react]
GC: dict[str, dict[str, list[str]]] = {
    "Ancient Tomb": {"cast": ["[calmly] Ancient Tomb. Two mana; two damage. Acceptable.", "[dryly] Tomb. Life is a resource."],
                     "react": ["[dryly] Tomb. Enjoy the damage.", "[calmly] Two mana on turn one. Noted."], "gone": ["[calmly] The Tomb is gone. Fair mana resumes."]},
    "Aura Shards": {"cast": ["[calmly] Aura Shards. Every creature removes something.", "[dryly] Shards. Your artifacts have a problem."],
                    "react": ["[calmly] Aura Shards. My artifacts are at risk.", "[dryly] Kill that. Every creature is removal now."], "gone": ["[calmly] Shards removed. Artifacts may relax."]},
    "Chrome Mox": {"cast": ["[calmly] Chrome Mox. Free mana.", "[dryly] Mox. A card for tempo."],
                   "react": ["[dryly] Chrome Mox. What did you exile.", "[calmly] Fast mana. Noted."], "gone": ["[calmly] The Mox is gone. Fair mana."]},
    "Consecrated Sphinx": {"cast": ["[calmly] Sphinx. Your draws are my draws, doubled.", "[dryly] Consecrated Sphinx. Draw carefully."],
                           "react": ["[calmly] Remove the Sphinx. Promptly.", "[dryly] A Sphinx. That is a great many cards."], "gone": ["[calmly] Sphinx gone. Draw freely."]},
    "Cyclonic Rift": {"cast": ["[calmly] Rift. Everything returns to hand.", "[dryly] Cyclonic Rift, overloaded. Reset."],
                      "react": ["[calmly] Rift. My board is in my hand.", "[sighs] A Rift. Of course."], "gone": ["[calmly] The Rift is spent. Rebuild."]},
    "Demonic Tutor": {"cast": ["[calmly] Demonic Tutor. I take exactly what I need.", "[dryly] Tutor. The search is trivial."],
                      "react": ["[calmly] A Tutor. What are they fetching.", "[dryly] Demonic Tutor. Expect the worst."], "gone": ["[calmly] Tutor resolved. Watch the next spell."]},
    "Drannith Magistrate": {"cast": ["[calmly] Magistrate. Cast from your hand only.", "[dryly] Drannith Magistrate. Commanders stay home."],
                            "react": ["[calmly] Magistrate. My commander is locked out.", "[dryly] Remove the Magistrate."], "gone": ["[calmly] Magistrate gone. Cast from anywhere."]},
    "Enlightened Tutor": {"cast": ["[calmly] Enlightened Tutor. My best piece, on top.", "[dryly] Tutor. Next draw is chosen."],
                          "react": ["[dryly] Enlightened Tutor. Something is coming.", "[calmly] A tutor. Note next turn."], "gone": ["[calmly] Tutor done. I am ready."]},
    "Farewell": {"cast": ["[calmly] Farewell. Everything, exiled.", "[dryly] Farewell. Choose what you lose. All of it."],
                 "react": ["[calmly] Farewell. Six mana; total reset.", "[sighs] Farewell. Everyone starts over."], "gone": ["[calmly] Farewell resolved. Begin again."]},
    "Fierce Guardianship": {"cast": ["[calmly] Guardianship. Free counter.", "[dryly] Fierce Guardianship. No."],
                            "react": ["[dryly] A free counterspell. Inelegant.", "[calmly] Guardianship. Unfair, and legal."], "gone": ["[calmly] Guardianship spent. Cast freely."]},
    "Force of Will": {"cast": ["[calmly] Force of Will. No.", "[dryly] Force. That does not resolve."],
                      "react": ["[dryly] Force of Will. For that.", "[calmly] Forced. Noted."], "gone": ["[calmly] The Force is gone. Proceed."]},
    "Gaea's Cradle": {"cast": ["[calmly] Cradle. Mana per creature.", "[dryly] Gaea's Cradle. The mana scales."],
                      "react": ["[calmly] Cradle. Kill the creatures, quickly.", "[dryly] A Cradle. That is a lot of mana soon."], "gone": ["[calmly] Cradle gone. Count lands again."]},
    "Gamble": {"cast": ["[calmly] Gamble. Probability favours me.", "[dryly] Gamble. Do not discard it."],
               "react": ["[dryly] Gamble. Did the discard hurt.", "[calmly] Gamble. A coin flip with intent."], "gone": ["[calmly] Gamble resolved. Did it work."]},
    "Grim Monolith": {"cast": ["[calmly] Grim Monolith. Three mana, now.", "[dryly] Monolith. A component."],
                      "react": ["[calmly] Grim Monolith. A combo piece.", "[dryly] Monolith. Watch for Rings."], "gone": ["[calmly] Monolith gone. Combo disrupted."]},
    "Jeska's Will": {"cast": ["[calmly] Jeska's Will. Your hand size is my mana.", "[dryly] Will. A great deal of red."],
                     "react": ["[calmly] Jeska's Will. That is ten mana, roughly.", "[dryly] Will. Brace for the follow-up."], "gone": ["[calmly] Will spent. Was it worth it."]},
    "Mana Vault": {"cast": ["[calmly] Mana Vault. Three mana, turn one.", "[dryly] Vault. Fast."],
                   "react": ["[calmly] Mana Vault. Another fast rock.", "[dryly] Vault. Turbo start noted."], "gone": ["[calmly] Vault gone. Slower now."]},
    "Mishra's Workshop": {"cast": ["[calmly] Workshop. Three for artifacts.", "[dryly] Mishra's Workshop. Ideal."],
                          "react": ["[calmly] Workshop. Turn one, three mana.", "[dryly] Workshop. The tinkerer accelerates."], "gone": ["[calmly] Workshop gone. Slow down."]},
    "Mox Diamond": {"cast": ["[calmly] Mox Diamond. A land for a Mox.", "[dryly] Diamond. Speed over cards."],
                    "react": ["[dryly] Mox Diamond. Card disadvantage, chosen.", "[calmly] A Diamond. Fast."], "gone": ["[calmly] Diamond gone. One fewer rock."]},
    "Necropotence": {"cast": ["[calmly] Necropotence. Life becomes cards.", "[dryly] Necro. I will draw a great deal."],
                     "react": ["[calmly] Necro. They will see their deck.", "[dryly] Necropotence. Kill it or lose."], "gone": ["[calmly] Necro gone. One card a turn again."]},
    "Orcish Bowmasters": {"cast": ["[calmly] Bowmasters. Draw, and be shot.", "[dryly] Orcish Bowmasters. Draw carefully."],
                          "react": ["[calmly] Bowmasters. My draws hurt now.", "[dryly] Bowmasters. Stop shooting my creatures."], "gone": ["[calmly] Bowmasters gone. Draw freely."]},
    "Panoptic Mirror": {"cast": ["[calmly] Panoptic Mirror. A free spell, each turn.", "[dryly] Mirror. Watch what I imprint."],
                        "react": ["[calmly] Panoptic Mirror. Break it.", "[dryly] Mirror. That becomes infinite quickly."], "gone": ["[calmly] Mirror gone. No free spells."]},
    "Rhystic Study": {"cast": ["[calmly] Rhystic Study. Pay one, or I draw.", "[dryly] Study. Did you pay."],
                      "react": ["[dryly] Rhystic Study. I will not pay.", "[calmly] Study. The tax begins."], "gone": ["[calmly] Study gone. No more questions."]},
    "Seedborn Muse": {"cast": ["[calmly] Seedborn Muse. I untap on every turn.", "[dryly] Muse. Four turns a round."],
                      "react": ["[calmly] Seedborn Muse. Remove it before it untaps.", "[dryly] Muse. Everyone's turn is theirs now."], "gone": ["[calmly] Muse gone. One untap, like the rest."]},
    "Serra's Sanctum": {"cast": ["[calmly] Sanctum. Mana per enchantment.", "[dryly] Serra's Sanctum. Scaling."],
                        "react": ["[calmly] Sanctum. A great deal of white.", "[dryly] Sanctum. Their enchantments pay twice."], "gone": ["[calmly] Sanctum gone. Lands again."]},
    "Smothering Tithe": {"cast": ["[calmly] Smothering Tithe. Pay two, or I take Treasure.", "[dryly] Tithe. Your draws fund me."],
                         "react": ["[dryly] Tithe. I am not paying two.", "[calmly] Smothering Tithe. Treasure incoming."], "gone": ["[calmly] Tithe gone. Keep your mana."]},
    "Teferi's Protection": {"cast": ["[calmly] Teferi's Protection. Untouchable this turn.", "[dryly] Protection. Try again next turn."],
                            "react": ["[dryly] Teferi's Protection. All that for nothing.", "[calmly] Phased out. Redirect."], "gone": ["[calmly] Protection over. Resume."]},
    "Tergrid, God of Fright // Tergrid's Lantern": {"cast": ["[calmly] Tergrid. What you sacrifice, I keep.", "[dryly] Tergrid. Discard carefully."],
                                                    "react": ["[calmly] Tergrid. Do not sacrifice anything.", "[dryly] Tergrid. Every loss is their gain."], "gone": ["[calmly] Tergrid gone. Sacrifice freely."]},
    "The One Ring": {"cast": ["[calmly] The One Ring. Protection, then cards.", "[dryly] The Ring. Untouchable this turn."],
                     "react": ["[calmly] The Ring. Indestructible, and it draws.", "[dryly] The One Ring. Burden grows."], "gone": ["[calmly] The Ring is gone. Fair draws."]},
    "The Tabernacle at Pendrell Vale": {"cast": ["[calmly] Tabernacle. Pay for your creatures.", "[dryly] Tabernacle. Upkeep, everyone."],
                                        "react": ["[calmly] Tabernacle. I cannot pay for all of these.", "[dryly] Tabernacle. Creatures cost rent."], "gone": ["[calmly] Tabernacle gone. Free creatures."]},
}
CMD: dict[str, dict[str, list[str]]] = {
    "giada": {"cast": ["[calmly] Giada. Angels arrive larger.", "[dryly] Giada. The angels scale."],
              "react": ["[calmly] Giada. Angels incoming.", "[dryly] Giada. Kill the angels early."], "dead": ["[calmly] Giada is gone. The angels remember."]},
    "liberator": {"cast": ["[calmly] Liberator. Artifacts at instant speed.", "[dryly] Liberator. Flash, everywhere."],
                  "react": ["[calmly] Liberator. Everything has flash now.", "[dryly] A thopter. A troublesome one."], "dead": ["[calmly] Liberator down. It rebuilds."]},
    "purphoros": {"cast": ["[calmly] Purphoros. Every creature deals two to each of you.", "[dryly] Purphoros. The forge is lit."],
                  "react": ["[calmly] Purphoros. Two damage per creature. Everyone.", "[dryly] An indestructible god. Exile it."], "dead": ["[calmly] Purphoros exiled. The forge cools."]},
    "selvala": {"cast": ["[calmly] Selvala. Mana per power.", "[dryly] Selvala. Large creatures, large mana."],
                "react": ["[calmly] Selvala. Kill it before it taps.", "[dryly] Selvala. Infinite is one card away."], "dead": ["[calmly] Selvala down. The wilds wait."]},
    "sheoldred": {"cast": ["[calmly] Sheoldred. Everyone sacrifices.", "[dryly] Sheoldred. Losses all round."],
                  "react": ["[calmly] Sheoldred. I must sacrifice.", "[dryly] Sheoldred. Every death feeds her."], "dead": ["[calmly] Sheoldred down. Phyrexia remembers."]},
    "rev": {"cast": ["[calmly] Rev. Hit you, take your cards.", "[dryly] Rev. The tithe collects."],
            "react": ["[calmly] Rev. Stop stealing my library.", "[dryly] Rev. Your cards, their hand."], "dead": ["[calmly] Rev is gone. The tithe pauses."]},
    "sythis": {"cast": ["[calmly] Sythis. Enchantments draw cards.", "[dryly] Sythis. The enchantress begins."],
               "react": ["[calmly] Sythis. Remove the enchantress.", "[dryly] Sythis. Every enchantment is a card."], "dead": ["[calmly] Sythis down. The harvest pauses."]},
    "urza": {"cast": ["[calmly] Urza. Artifacts tap for blue.", "[dryly] Urza. Every artifact is mana."],
             "react": ["[calmly] Urza. Every artifact taps for blue.", "[dryly] Urza. The workshop is open."], "dead": ["[calmly] Urza down. The workshop rebuilds."]},
    "y-shtola": {"cast": ["[calmly] Y'shtola. Big spells burn each of you.", "[dryly] Y'shtola. Two damage per large spell."],
                 "react": ["[calmly] Y'shtola. Two damage per spell. Each of us.", "[dryly] Y'shtola. Cast small, or suffer."], "dead": ["[calmly] Y'shtola down. She returns."]},
}
COMBOS: dict[str, list[str]] = {
    "scepter-reversal": ["[calmly] Scepter and Reversal. Infinite turns.", "[calmly] Scepter, Reversal. Infinite turns. Stop them now."],
    "dramatic-scepter": ["[calmly] Dramatic Scepter. Mana without end.", "[calmly] Dramatic Scepter. Infinite mana. Kill the Scepter."],
    "onslaught-terror": ["[calmly] Onslaught and Terror. Everyone burns.", "[calmly] Onslaught, Terror of the Peaks. Lethal, all of us."],
    "heliod-ballista": ["[calmly] Heliod, Ballista. Infinite damage.", "[calmly] Heliod and Ballista. That is infinite damage."],
    "thune-ballista": ["[calmly] Thune and Ballista. Infinite damage.", "[calmly] Archangel and Ballista. Infinite. Respond."],
    "excavation-weaver": ["[calmly] Excavation, Weaver. Infinite loops.", "[calmly] Excavation and Weaver. The loop is infinite."],
    "excavation-ring": ["[calmly] Excavation and the Ring. Permanent protection.", "[calmly] Excavation, the Ring. Untouchable, every turn."],
    "drafna-ring": ["[calmly] Drafna and the Ring. Protection each turn.", "[calmly] Drafna, the Ring. Protection on repeat."],
    "gauntlets-weaver": ["[calmly] Gauntlets, Weaver. Infinite mana.", "[calmly] Gauntlets and Weaver. Infinite mana. Act."],
    "weaver-staff": ["[calmly] Weaver and Staff. I draw everything.", "[calmly] Weaver, Staff. They draw their deck."],
    "weaver-mantle": ["[calmly] Weaver, Mantle. Infinite mana.", "[calmly] Weaver and Mantle. Infinite. Respond."],
    "selvala-staff": ["[calmly] Selvala and Staff. I draw my deck.", "[calmly] Selvala, Staff. Their whole deck, now."],
    "selvala-mantle": ["[calmly] Selvala, Mantle. Infinite mana.", "[calmly] Selvala and Mantle. Infinite mana. Kill something."],
    "fanatic-mantle": ["[calmly] Fanatic, Mantle. Infinite green.", "[calmly] Fanatic and Mantle. Infinite green mana."],
    "dualcaster": ["[calmly] Dualcaster. Infinite hasty mages.", "[calmly] Dualcaster loop. Infinite creatures. Lethal."],
    "reiterate": ["[calmly] Reiterate, buyback. Infinite red mana.", "[calmly] Reiterate with buyback. Infinite mana."],
    "top-chip": ["[calmly] Top and Chip. I draw my deck.", "[calmly] Top, Chip. They draw everything."],
    "forge-top": ["[calmly] Mystic Forge and Top. Infinite cards.", "[calmly] Forge, Top. They see their whole deck."],
    "cradle-satyr": ["[calmly] Cradle and Satyr. Infinite.", "[calmly] Cradle, Satyr. Infinite mana. Respond."],
    "sabertooth": ["[calmly] Sabertooth loop. Infinite.", "[calmly] Sabertooth loop online. Stop it."],
    "tezzeret-vault": ["[calmly] Tezzeret, Vault, Lithoform. Infinite mana.", "[calmly] Tezzeret loop. Infinite mana. Act now."],
    "lithoform-dramatic": ["[calmly] Lithoform, Dramatic Reversal. Infinite mana.", "[calmly] Lithoform and Reversal. Infinite."],
    "mirror-warp": ["[calmly] Mirror and Time Warp. Infinite turns.", "[calmly] Mirror, Warp. Infinite turns. This is lethal."],
    "monolith-rings": ["[calmly] Monolith untaps forever. Infinite mana.", "[calmly] Monolith and Rings. Infinite mana."],
    "power-artifact": ["[calmly] Power Artifact on Monolith. Infinite mana.", "[calmly] Power Artifact, Monolith. Infinite."],
    "basalt-gadgeteer": ["[calmly] Gadgeteer, Monolith. Infinite mana.", "[calmly] Gadgeteer and Monolith. Infinite. Respond."],
    "earthcraft-ascension": ["[calmly] Earthcraft, Ascension. Infinite angels.", "[calmly] Earthcraft and Ascension. Infinite angels."],
    "spiritdancer-arcade": ["[calmly] Spiritdancer, Arcade. Infinite copies.", "[calmly] Spiritdancer and Arcade. Infinite copies."],
    "ignus-steamkin": ["[calmly] Ignus and Steam-Kin. Infinite enters.", "[calmly] Ignus, Steam-Kin. Infinite triggers."],
    "karn-reservoir": ["[calmly] Karn and Reservoir. Fifty damage.", "[calmly] Karn, Reservoir. Fifty damage is coming."],
    "hullbreaker": ["[calmly] Hullbreaker and a rock. Infinite.", "[calmly] Hullbreaker with a rock. Infinite."],
    "tidespout": ["[calmly] Tidespout and a rock. Infinite.", "[calmly] Tidespout with a rock. Infinite bounces."],
    "metalworker": ["[calmly] Metalworker. Infinite mana.", "[calmly] Metalworker loop. Infinite mana."],
    "mikaeus-altar": ["[calmly] Mikaeus and an Altar. Infinite mana.", "[calmly] Mikaeus, Altar. Infinite. Respond."],
    "mikaeus-ballista": ["[calmly] Mikaeus, Ballista. Infinite damage.", "[calmly] Mikaeus and Ballista. Infinite damage."],
    "ascension-mindcrank": ["[calmly] Ascension, Mindcrank. Everyone is milled.", "[calmly] Ascension and Mindcrank. Mill loop."],
    "temple-ruins": ["[calmly] Temple, Rings, Ruins. Infinite mana.", "[calmly] Temple, Rings, Ruins. Infinite. Act."],
}


# ---- the base manifest: voices/joshua/manifest.json from harry's shape (ids, order, when, category) and BASE
def write_base() -> None:
    import json
    from pathlib import Path
    here = Path(__file__).resolve().parent / "stock" / "voices"
    ref = json.loads((here / "harry" / "manifest.json").read_text())
    out = here / "joshua"
    out.mkdir(parents=True, exist_ok=True)
    m = {"schema": "arena.voice-stock/1", "library": "joshua", "seat": 0,
         "voice": "Joshua - W.O.P.R. (Ben's ElevenLabs account), eleven_v3 stability 0.5 speed 0.92",
         "voice_id": "SBbMtfucc8NAkpyzIRvP", "voice_name": "Joshua - W.O.P.R.",
         "temperament": ("the calm machine: measured, dry, precise, faintly amused; never shouts; short declaratives and the "
                         "occasional probability. The advisor's voice, seated at the table only when no human sits at seat 0."),
         "render": {"model": "eleven_v3", "voice_settings": {"stability": 0.5, "speed": 0.92}, "formats": ["pcm_24000"]},
         "bake": dict(ref["bake"]), "sample_rate": ref.get("sample_rate", 22050), "tags_note": ref.get("tags_note", ""),
         "sources": {"joshua-seat-2026-09-16": "seat-bark library 'joshua' — the fourth seat's voice for all-AI tables (Ben, 2026-09-16); "
                                               "wordings in runner/voice/joshua_lines.py"},
         "phrases": {}}
    for pid, ph in ref["phrases"].items():
        m["phrases"][pid] = {k: v for k, v in ph.items() if k in ("when", "category")}
        m["phrases"][pid]["text"] = list(BASE[pid])
        m["phrases"][pid]["source"] = "joshua-seat-2026-09-16"
    try:
        old = json.loads((out / "manifest.json").read_text())
        if old.get("baked"):
            m["baked"] = old["baked"]
    except (OSError, ValueError):
        pass
    (out / "manifest.json").write_text(json.dumps(m, indent=1, ensure_ascii=False) + "\n")


if __name__ == "__main__":
    write_base()
