package forge.arena.bindgen;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import forge.arena.combo.ExecutorBindings;
import forge.arena.combo.SimResult;
import forge.arena.combo.TapForManaUntapLoop;
import forge.arena.prep.ClaudeClient;

/**
 * Gate 3.5 bindgen (plan §3/§9 W1): executor bindings for combos the library
 * doesn't cover yet, generated by ONE Claude call per distinct combo — ever —
 * and gated by the pipeline the plan mandates: schema/lint (the archetype
 * constructor is the lint), then SANDBOX SIM VERIFICATION (the injected
 * {@link Verifier} runs the binding's validate() on a real board — the
 * engine is the oracle). A binding that fails verification gets ONE repair
 * retry with the failure appended; a second failure lands the combo in
 * {@code unbound} with a bindgen-failed note — hallucinations structurally
 * cannot reach executable. Novel-archetype proposals ({@code archetype:
 * null}) go to a review file, never to code.
 *
 * <p>Cache-first: combos already bound OR already recorded unbound cost zero
 * calls. The library file is only rewritten when something was added, so a
 * fully-cached run is byte-identical (BindingLibraryCacheTest).
 */
public final class BindGen {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    /** The hand-written archetypes bindgen may parameterize (closed set). */
    public static final List<String> ARCHETYPES = List.of(TapForManaUntapLoop.ARCHETYPE);

    /** Engine-side sandbox verification, injectable so tests control it. */
    public interface Verifier {
        SimResult verify(ExecutorBindings.Binding binding) throws IOException;
    }

    public record Result(int generated, int failedVerification, int cached, int proposals,
            List<String> notes) {
    }

    private BindGen() {
    }

    public static Result run(Path dossierDir, Path bindingsFile, ClaudeClient client,
            Verifier verifier) throws IOException {
        JsonNode combos = MAPPER.readTree(dossierDir.resolve("combos.json").toFile());
        Map<String, String> oracle = oracleTexts(dossierDir);
        ObjectNode library = (ObjectNode) MAPPER.readTree(bindingsFile.toFile());
        ExecutorBindings existing = ExecutorBindings.load(bindingsFile);

        int generated = 0;
        int failed = 0;
        int cached = 0;
        int proposals = 0;
        List<String> notes = new ArrayList<>();
        boolean dirty = false;

        for (JsonNode combo : combos.get("combos")) {
            String comboId = combo.get("id").asText();
            if (existing.forCombo(comboId).isPresent() || existing.unbound().contains(comboId)) {
                cached++;
                continue; // zero calls, ever (plan: O(distinct combos))
            }
            if (combo.has("template_requirements")) {
                notes.add(comboId + ": template pieces — not bindable by named cards");
                continue;
            }

            String system = systemPrompt();
            String user = userPrompt(combo, oracle, library);
            String requestSha = sha256(client.requestBody(system, user));
            ObjectNode binding = null;
            String failure = null;
            SimResult verdict = null;
            for (int attempt = 0; attempt < 2 && binding == null; attempt++) {
                String prompt = failure == null ? user
                        : user + "\n\nYour previous binding failed: " + failure
                                + "\nRespond again with ONLY the corrected JSON object.";
                JsonNode parsed = parseJson(client.complete(system, prompt));
                if (parsed == null) {
                    failure = "not parseable as a JSON object";
                    continue;
                }
                if (parsed.hasNonNull("proposal") || parsed.path("archetype").isNull()) {
                    appendProposal(bindingsFile, comboId, parsed.path("proposal").asText("?"));
                    proposals++;
                    failure = "PROPOSAL"; // recorded; no retry
                    break;
                }
                ObjectNode candidate = lint(parsed, comboId);
                if (candidate == null) {
                    failure = "failed lint: unknown archetype or malformed/incomplete params";
                    continue;
                }
                // the oracle: the engine either proves the loop or refuses it
                verdict = verifier.verify(toBinding(candidate));
                if (verdict.isProfitable()) {
                    binding = candidate;
                } else {
                    failure = "sim verification " + verdict.status()
                            + (verdict.blockedBy() != null ? " blocked_by=" + verdict.blockedBy() : "");
                }
            }

            if (binding != null) {
                ObjectNode provenance = binding.putObject("provenance");
                provenance.put("generated_by", "bindgen/1");
                provenance.put("model", client.model());
                provenance.put("request_sha256", requestSha);
                provenance.put("sim_cycles", verdict.cycles());
                ((ArrayNode) library.withArray("bindings")).add(binding);
                generated++;
                dirty = true;
                notes.add(comboId + ": bound + sim-verified (" + verdict.cycles() + " cycles)");
            } else if (!"PROPOSAL".equals(failure)) {
                failed++;
                dirty = true;
                ((ArrayNode) library.withArray("unbound")).add(comboId);
                notes.add(comboId + ": binding_gen_failed — " + failure + " (detection-only)");
            }
        }

        if (dirty) {
            MAPPER.writerWithDefaultPrettyPrinter().writeValue(bindingsFile.toFile(), library);
        }
        return new Result(generated, failed, cached, proposals, notes);
    }

    /** Schema/lint gate: known archetype, constructible params. Null = refused. */
    static ObjectNode lint(JsonNode parsed, String comboId) {
        if (!ARCHETYPES.contains(parsed.path("archetype").asText()) || !parsed.has("params")) {
            return null;
        }
        Map<String, String> params = new LinkedHashMap<>();
        for (Iterator<Map.Entry<String, JsonNode>> it = parsed.get("params").fields(); it.hasNext();) {
            Map.Entry<String, JsonNode> e = it.next();
            params.put(e.getKey(), e.getValue().asText());
        }
        try {
            new TapForManaUntapLoop(params, parsed.path("entry_phase").asText("MAIN1"));
        } catch (RuntimeException e) {
            return null; // missing/malformed params — the constructor is the lint
        }
        ObjectNode binding = MAPPER.createObjectNode();
        binding.put("combo_id", comboId);
        binding.put("archetype", parsed.get("archetype").asText());
        binding.set("params", parsed.get("params").deepCopy());
        if (parsed.has("payoffs") && parsed.get("payoffs").isArray()) {
            binding.set("payoffs", parsed.get("payoffs").deepCopy());
        }
        binding.put("entry_phase", parsed.path("entry_phase").asText("MAIN1"));
        return binding;
    }

    static ExecutorBindings.Binding toBinding(ObjectNode node) {
        Map<String, String> params = new LinkedHashMap<>();
        for (Iterator<Map.Entry<String, JsonNode>> it = node.get("params").fields(); it.hasNext();) {
            Map.Entry<String, JsonNode> e = it.next();
            params.put(e.getKey(), e.getValue().asText());
        }
        List<String> payoffs = new ArrayList<>();
        if (node.has("payoffs")) {
            node.get("payoffs").forEach(p -> payoffs.add(p.asText()));
        }
        return new ExecutorBindings.Binding(node.get("combo_id").asText(),
                node.get("archetype").asText(), params, payoffs,
                node.path("entry_phase").asText("MAIN1"), List.of());
    }

    private static String systemPrompt() {
        return "You parameterize combo-executor bindings for a Magic: The Gathering simulator."
                + " You respond with ONLY a JSON object — no prose, no markdown fences. You may"
                + " ONLY select an archetype from the closed set given in the request and fill"
                + " its params from the combo's actual cards; if none fits, respond"
                + " {\"archetype\": null, \"proposal\": \"<one-paragraph description>\"}."
                + " Never invent card names; costs come from the oracle text. Your binding will"
                + " be verified by simulation before use — a wrong binding is discarded.";
    }

    private static String userPrompt(JsonNode combo, Map<String, String> oracle, JsonNode library) {
        StringBuilder sb = new StringBuilder();
        sb.append("ARCHETYPES (closed set): ").append(String.join(", ", ARCHETYPES)).append('\n');
        sb.append("""
                TapForManaUntapLoop params: engine (the permanent tapped for mana),
                untapper, activation_cost (engine's mana-ability cost, e.g. "{G}"),
                untap_cost (the untap activation's mana cost), untap_ability_host
                ("engine" when the untapper GRANTS its ability to the engine, e.g.
                equipment; else "untapper"), untap_targets_engine ("true" when the
                untap ability targets), untapper_reset_cost (only if the untapper
                must re-ready itself, e.g. "{1}"), attach_cost (equip cost when the
                untapper is equipment), engine_mana_value / untapper_mana_value
                (mana value of casting each piece), self_pump_per_cycle (power the
                engine gains per cycle from the untap activation, else "0"),
                pool_color (the engine's production color letter).
                Respond: {"archetype", "params", "payoffs" (win-conversion cards
                from the combo's steps, may be []), "entry_phase"}.

                VERIFIED EXAMPLES (few-shot):
                """);
        JsonNode bindings = library.path("bindings");
        for (int i = 0; i < Math.min(2, bindings.size()); i++) {
            sb.append(bindings.get(i).toString()).append('\n');
        }
        sb.append("\nCOMBO TO BIND:\n").append(combo.toString()).append('\n');
        sb.append("\nORACLE TEXT OF THE PIECES:\n");
        for (JsonNode card : combo.path("cards")) {
            String name = card.path("name").asText();
            sb.append(name).append(": ").append(oracle.getOrDefault(name, "(not found)"))
                    .append('\n');
        }
        return sb.toString();
    }

    private static Map<String, String> oracleTexts(Path dossierDir) throws IOException {
        Map<String, String> oracle = new LinkedHashMap<>();
        JsonNode deckCards = MAPPER.readTree(dossierDir.resolve("deck-cards.json").toFile());
        for (JsonNode card : deckCards.get("cards")) {
            oracle.put(card.get("name").asText(), card.path("oracle_text").asText(""));
        }
        return oracle;
    }

    private static void appendProposal(Path bindingsFile, String comboId, String proposal)
            throws IOException {
        Path file = bindingsFile.resolveSibling("bindgen-proposals.jsonl");
        Map<String, Object> row = new LinkedHashMap<>();
        row.put("combo_id", comboId);
        row.put("proposal", proposal);
        Files.writeString(file, MAPPER.writeValueAsString(row) + "\n",
                StandardCharsets.UTF_8, java.nio.file.StandardOpenOption.CREATE,
                java.nio.file.StandardOpenOption.APPEND);
    }

    private static JsonNode parseJson(String text) {
        String candidate = text.strip();
        if (candidate.startsWith("```")) {
            int start = candidate.indexOf('\n');
            int end = candidate.lastIndexOf("```");
            if (start >= 0 && end > start) {
                candidate = candidate.substring(start + 1, end).strip();
            }
        }
        try {
            JsonNode parsed = MAPPER.readTree(candidate);
            return parsed.isObject() ? parsed : null;
        } catch (IOException e) {
            return null;
        }
    }

    private static String sha256(String body) {
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256")
                    .digest(body.getBytes(StandardCharsets.UTF_8));
            StringBuilder hex = new StringBuilder();
            for (byte b : digest) {
                hex.append(String.format("%02x", b));
            }
            return hex.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }
}
