#!/bin/bash
# Launch an arena batch: batch.sh <batch-config.json>
# JVM flags (plan W6): orchestrator is light; each worker gets -Xmx2g
# (override per config "worker_heap"). Workers are separate JVMs — one game
# at a time per JVM keeps MyRandom seeding deterministic.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CONFIG="${1:?usage: batch.sh <batch-config.json>}"
export JAVA_HOME="${JAVA_HOME:-/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home}"

# classpath.txt is generated by the reactor build (maven-dependency-plugin in
# forge-arena/pom.xml) — a standalone dependency:build-classpath cannot resolve
# the fork's ci-friendly ${revision} parent poms, so we build instead.
CP_FILE="$REPO_ROOT/forge-arena/target/classpath.txt"
if [ ! -f "$CP_FILE" ] || [ "$REPO_ROOT/forge-arena/pom.xml" -nt "$CP_FILE" ]; then
  echo "building forge-arena (generates classpath.txt)..."
  (cd "$REPO_ROOT" && mvn -pl forge-arena -am install -DskipTests -Darena.skip.tests=true -Dcheckstyle.skip=true -q)
fi
CP="$REPO_ROOT/forge-arena/target/classes:$(cat "$CP_FILE")"

cd "$REPO_ROOT"
exec "$JAVA_HOME/bin/java" -Xmx512m -cp "$CP" forge.arena.harness.BatchMain "$CONFIG"
