#!/bin/bash
# arena prep v1 (plan §3, v3.3): compile a deck dossier through Gates 0-3
#   prep.sh <input-list> --id <deck-id> [PrepMain options...]
#   prep.sh --check <dossier-dir>
# All arguments pass through to forge.arena.prep.PrepMain (see its usage).
# Network: one Commander Spellbook call per new deck hash (cache-first);
# --offline forbids even that. Exit: 0 batch-ready, 1 gate failure, 2 usage.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
[ $# -ge 1 ] || { echo "usage: prep.sh <input-list> --id <deck-id> [options...] | prep.sh --check <dossier-dir>"; exit 2; }
export JAVA_HOME="${JAVA_HOME:-/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home}"

# classpath.txt is generated by the reactor build (see batch.sh for why a
# standalone dependency:build-classpath cannot work here)
CP_FILE="$REPO_ROOT/forge-arena/target/classpath.txt"
if [ ! -f "$CP_FILE" ] || [ "$REPO_ROOT/forge-arena/pom.xml" -nt "$CP_FILE" ]; then
  echo "building forge-arena (generates classpath.txt)..."
  (cd "$REPO_ROOT" && mvn -pl forge-arena -am install -DskipTests -Dcheckstyle.skip=true -q)
fi
CP="$REPO_ROOT/forge-arena/target/classes:$(cat "$CP_FILE")"

cd "$REPO_ROOT"
exec "$JAVA_HOME/bin/java" -Xmx2g -cp "$CP" forge.arena.prep.PrepMain "$@"
